### ISSUE TITLE
Checksum error on raw_30s_audio05

### ISSUE THREAD

**Issue by rfalcon100** [MTG/mtg-jamendo-dataset#11]
When using the provided download script to download the raw 30s audio data set via google drive, I keep getting the same checksum error for one file.

/data/download/raw_30s_audio-05.tar 

![image](https://user-images.githubusercontent.com/47180383/59679475-9c6e9600-91d7-11e9-9637-272a2b16fc11.png)

Can you confirm is there is an issue with the source file?

**Comment by dbogdanov** [comment]
Hello @rfalcon100, yes, we have identified this issue and are validating the checksums.

**Comment by dbogdanov** [comment]
This should work now. Please, let us know if you have any other issues.

**Comment by rfalcon100** [comment]
It is working now. All files were downloaded correctly and the checksums match. Thanks.
