### ISSUE TITLE
Best way to load raw audio data?

### ISSUE THREAD

**Issue by rfalcon100** [MTG/mtg-jamendo-dataset#19]
Is there a recommended way of loading the data as raw audio? I am working with Pytorch, and tried using [torchaudio](https://github.com/pytorch/audio), generating a dataset that reads individual mp3 files, in a similar way to the dataset in the baseline code.

However, this is really slow, as it seems the workers are busy decoding the mp3 files. 

Would it make sense to preprocess all files and save them as `npy`or `torch.Tensor` files, while the dataset only loads them? The main issue is that it would require significant more storage than the raw dataset stored as mp3.

**Comment by philtgun** [comment]
It depends on what do you want to do with audio prior to learning. We use [Essentia](https://essentia.upf.edu/) to read audio files and compute the spectrograms (see [`melspectrograms.py`](https://github.com/MTG/mtg-jamendo-dataset/blob/master/scripts/melspectrograms.py)). 

If you want to work with raw audio, I would say that indeed there is a tradeoff between speed and storage. It is a good practice to do the preprocessing separately from training (cutting or selecting regions) and save data that is ready for training as `.npy` (that's what we did for 30s spectrograms).

Any other comments, @minzwon?

**Comment by minzwon** [comment]
I've never used `torchaudio` yet. I usually store the raw audio as `.npy` file. This is useful especially when you train the network with shorter chunks (i.e. 8 seconds instead of 30 seconds). In this case, I also recommend you to check `mmap_mode` of `np.load`.

**Comment by rfalcon100** [comment]
It seems that preprocessing the files saving them as `.npy` makes sense then. That said, have you tried saving all individual `.npy`files as a single lmdb file?  
Depending on the filesystem, this should be faster, as the extra cost for accessing a file is done only once. However, in my tests this is actually slower than just loading individual `.npy`files.
