### ISSUE TITLE
No such file or directory: '../../data/splits/split-0/all_train_dict.pickle' when reproducing experiments

### ISSUE THREAD

**Issue by expectopatronum** [MTG/mtg-jamendo-dataset#20]
Hi,
I tried to reproduce your experiments as described in the README of your repository:
`python scripts/baseline/main.py --mode 'TRAIN'`

I get the following error:
**No such file or directory: '../../data/splits/split-0/all_train_dict.pickle'** 
Did I miss running some preprocessing script?
Thanks for your help!
Best regards,
Verena

**Comment by minzwon** [comment]
Hi,

From `scripts/baseline/get_npy.py`, you can find the `run` function.
That will generate the pickle files that you need.

**Comment by expectopatronum** [comment]
Hi,
thanks for your quick response. The script contains a hardcoded path `'/home/minz/Developer/data/jamendo/npy'`. What should I replace this with?
I have downloaded the following data: `python scripts/download/download.py --dataset autotagging_moodtheme --type audio /home/verena/shared/MTG-Jamendo/audio/ --unpack --remove` which does not contain a npy directory. 
I was wondering if I might need to download the preprocessed melspecs for this script to work but I wanted to verify it first before downloading that much data.
Thanks and best regards,
Verena

**Comment by minzwon** [comment]
Sorry for the late response. I missed the notification. 
You should put your path to the spectrogram. You can download the spectrograms or you can do your own preprocessing using the audio files.

I updated the `get_npy.py` so that you can simply run:
 `python get_npy.py run 'your_path_to_spectrogram_npy'`
