### ISSUE TITLE
google drive shareable link to the directionary containing 100 zip files

### ISSUE THREAD

**Issue by yilunzhao** [MTG/mtg-jamendo-dataset#21]
Hi, I really appreciate your work! However, when I am trying to download the dataset, an error occurs: `Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.`
I wonder whether it's possible to provide google drive shareable link which contains the whole 100 zip files, so I can first save it into my drive and then download. Thank!

**Comment by philtgun** [comment]
Hello! Yes, that is unfortunately internal limitations by Google and we cannot do much about that. For now, you can try downloading from MTG, but it might be slower. We are also currently looking for the better hosting solution, so hopefully, in the near future, we can provide more mirrors.

**Comment by prachiisc** [comment]
Hi,
I am trying to download the data from google drive and getting this error !


Downloading autotagging_moodtheme from GDrive
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1ZodEoas7S-RS8CRNWj14LzgTKeMX9moO 

Can you suggest the solution as mtg is taking lot of time to download ?

**Comment by alastair** [comment]
Hi,
We've recently added a new download location for the dataset which should be much faster than the existing "mtg" mirror. Please try the download script with the `--from mtg-fast` flag

**Comment by helenacuesta** [comment]
Hi @alastair, 
Just tried to download with `--from mtg-fast` in the last version of the repo but it looks like the file structure in this new location doesn't follow the same file structure, leading to `404 Not Found`. From trying to run it like this, I get the following print:

`From: https://cdn.freesound.org/mtg-jamendo/autotagging_moodtheme/audio/autotagging_moodtheme_audio-00.tar`

But navigating the URL directly in the browser, the audio files are in subfolders `00/, 01/`...in the `audio/` [directory](https://cdn.freesound.org/mtg-jamendo/autotagging_moodtheme/audio/), so no `.tar` files are found. Compared to the `--from mtg` location, it looks like the script is calling them using the same URLs although they are different.

I might be missing something here, but is this expected?
Thanks!

**Comment by alastair** [comment]
thanks @helenacuesta for letting us know about this. I didn't realise that the location where I copied the audio from was uncompressed instead of set up in the tar files. I've copied the `autotagging_moodtheme_audio` files over now, and am checking the other folders to make sure that they correctly mirror the MTG download location

**Comment by aiXia121** [comment]
mtg-fast , resulting 404

**Comment by alastair** [comment]
Thanks for the notification, @aiXia121. We were also missing the audio files for the raw_30s collection. I've added these and tested all 6 download combinaitions.

**Comment by dbogdanov** [comment]
Disabled Google Drive downloads in 5e80e0c0009decd279dd7cf67d1d2711a69c0c74. Use `mtg` or `mtg-fast` mirrors for downloads.
