### ISSUE TITLE
Issue with downloading the data

### ISSUE THREAD

**Issue by infinitemugen** [MTG/mtg-jamendo-dataset#22]
I have been trying to download the data using Google Colab through the following command (as given in your repository's README):

`!python3 mtg-jamendo-dataset/scripts/download/download.py --dataset autotagging_moodtheme --type melspecs "/content/gdrive/My Drive/MediaEvalData" --unpack --remove`

This produces the following error (after downloading the first few files): 
```
Permission denied: https://drive.google.com/uc?id=1db60h1XiNYkIpUdPpXeta3stAsUBbGtT
Maybe you need to change permission over 'Anyone with the link'?
Traceback (most recent call last):
  File "mtg-jamendo-dataset/scripts/download/download.py", line 136, in <module>
    download(args.dataset, args.type, args.download_from, args.outputdir, args.unpack, args.remove)
  File "mtg-jamendo-dataset/scripts/download/download.py", line 73, in download
    if compute_sha256(output) != sha256_tars[filename]:
  File "mtg-jamendo-dataset/scripts/download/download.py", line 19, in compute_sha256
    with open(filename, 'rb') as f:
```
I request you to look into this issue. I am aware that this could be an issue on Google's end as well, and was wondering if there is a way around this, for the time being.

**Comment by alastair** [comment]
This is likely related to https://github.com/MTG/mtg-jamendo-dataset/issues/21, please use the alternate download link at https://github.com/MTG/mtg-jamendo-dataset#downloading-the-data
