### ISSUE TITLE
Conflicting dependencies in scripts/requirements.txt

### ISSUE THREAD

**Issue by Bomme** [MTG/mtg-jamendo-dataset#27]
The PR https://github.com/MTG/mtg-jamendo-dataset/pull/26 introduced a new minor version for `urllib3` which is not compatibel with the required `requests` version. 

```
ERROR: Cannot install -r scripts/requirements.txt (line 16) and urllib3==1.26.5 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

I guess this mix of pinned versions with occasional version bumps might lead to confusion among users.
Why not 
1. rename the `requirements.txt` file to something like `requirements-to-reproduce.txt` and
2. add a new `requirements.txt` file that only specifies versions for packages that this project directly depends on (i.e. this project only depends on `requests` which in turn depends on `urllib3`)

If that is not an option, the conflict can be resolved by either 
1. updating requests to [`requests~=2.25.0`](https://docs.python-requests.org/en/latest/community/updates/#id3) or
2. downgrading urllib3 to `urllib3~=1.25.0`

**Comment by philtgun** [comment]
Bumped requests version in 31507d6, nothing seems to be broken
