### ISSUE TITLE
Dataset in a lossless format

### ISSUE THREAD

**Issue by gogo9th** [MTG/mtg-jamendo-dataset#31]
Hi,

Thanks very much for this great dataset. 
I am working on a research project that requires lossless music files as input. I wonder if there is any way for us (or me) to get a .wav or .flac lossless version of your dataset by any chance.

**Comment by gogo9th** [comment]
I am sorry for my late reply.. and thanks very much for your useful tip. I'm glad to learn that uncompressed high-quality tracks are available. 

About your website's APIs, I wonder if you could please give me a tip for the following 2 types of user requests:

1. Retrieve all tracks of an uncompressed format
2. An example of downloading a particular track among the ones retrieved from #1. 

I really appreciate your support.

**Comment by alastair** [comment]
Hi, 
Please note that this dataset is not an official product of Jamendo, who hosts the data. This dataset is an independent project developed by an academic research group.

You may find this repository useful for some example python code to download uncompressed jamendo audio: https://github.com/AudioCommons/jamendo-downloader

**Comment by gogo9th** [comment]
Thanks for the URL of the new repository. 

When I run it, I get the following :

```
:Desktop/jamendo-downloader$ python3 getplaylist.py track_0000948 out.json
offset 0
results is empty
Done
```

Do you have any idea? I wonder if this is because I have to set the API key to some value (?) in `config.py`.

**Comment by gogo9th** [comment]
I created an account from Jamendo and got the client ID 4044a455. Now I can download tracks. Thanks very much!
