### ISSUE TITLE
Different sample rate in melspec computation

### ISSUE THREAD

**Issue by heydarshahi** [MTG/mtg-jamendo-dataset#38]
In the [`melspectrograms.py`](https://github.com/MTG/mtg-jamendo-dataset/blob/8797b3aa676ff8fbffb38efc4b1018e82a7b3beb/scripts/melspectrograms.py#L8) script the loading sampleRate is set to 12000. However, in [`get_npy.py`](https://github.com/MTG/mtg-jamendo-dataset/blob/8797b3aa676ff8fbffb38efc4b1018e82a7b3beb/scripts/baseline/get_npy.py#L41) sample rate is 16000. Is this downsampling just for faster computation or is there another reason for this that I'm missing?

**Comment by dbogdanov** [comment]
This is a mistake inside `get_npy.py`. This value is computed for information purposes only, the `duration` is not used anywhere else in the code for the baseline.
