### ISSUE TITLE
Checksums not matching in raw30s/audio-low

### ISSUE THREAD

**Issue by giorgioskij** [MTG/mtg-jamendo-dataset#39]
When I download the raw30s/audio-low shards (from both mtg and mtg-fast) I get multiple checksums that don't match. The first not matching is 09, and then many others.
Is this a problem of checksums not updated? 
I can provide a full list of the ones that don't match, if needed.
Thank you!

**Comment by dbogdanov** [comment]
I did a test download with `python3 scripts/download/download.py --dataset raw_30s --type audio-low downloads --unpack` and could not reproduce this issue. All `tar` archives have correct checksums.

**Comment by giorgioskij** [comment]
After pulling the last version, I can confirm that everything works ok! Maybe it got fixed in the recent commits, or it was just some weird issue on my end. Anyways, I think this can be closed
