### ISSUE TITLE
Licenses

### ISSUE THREAD

**Issue by wagnew3** [MTG/mtg-jamendo-dataset#56]
Hello,

The readme says individual audio file licenses are availible in audio_licenses.txt, but I cannot find this file--could you point me to it?

Some audio files in this dataset (ex. https://www.jamendo.com/track/214/intro-chiante) seem to now be under the Jamendo license, not a CC license. Has the licensing changed?

Thank you!

**Comment by dbogdanov** [comment]
Hi @wagnew3,

The `audio_licenses.txt` file is located in the root folder of the repository: https://github.com/MTG/mtg-jamendo-dataset/blob/master/audio_licenses.txt.

We are not aware of any changes to the licensing on the Jamendo website, but such changes could occur. We report the licenses that the tracks had at the time of compiling the dataset.
