### ISSUE TITLE
Add info about code and complete results for auto-tagging baselines

### ISSUE THREAD

**Issue by dbogdanov** [MTG/mtg-jamendo-dataset#8]
Add info about code and complete results for baselines to README in the section: https://github.com/MTG/jamendo-dataset#reproduce-experiments

**Comment by rfalcon100** [comment]
Quick quesiton: is the baseline code final? It appears to be looking for some 'base_filtered_by_artists-train.tsv' files, and an 'all' subset that I cannot find.

**Comment by dbogdanov** [comment]
@minzwon

**Comment by minzwon** [comment]
I will check it during the weekend.

**Comment by minzwon** [comment]
Hi @rfalcon100 ,
I think filenames and paths have been changed, so I fixed it. Now it works well with current filenames.

**Comment by rfalcon100** [comment]
It is working now, thanks.
